
import java.awt.Component;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;



public class SplitterLineUI extends javax.swing.JFrame {

    /**
     * Creates new form SplitterLineUI
     */
    public SplitterLineUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Packages = new javax.swing.JPanel();
        PackageListing = new javax.swing.JScrollPane();
        packagesToProcess = new javax.swing.JList<>();
        newPackageButton = new javax.swing.JButton();
        packetProgressBar = new javax.swing.JProgressBar();
        Maintenance = new javax.swing.JPanel();
        EmergencyButton = new javax.swing.JToggleButton();
        EmergencyButtonText = new javax.swing.JLabel();
        ConveyorText = new javax.swing.JLabel();
        ConveyorButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SplitterLine Interface");
        setSize(new java.awt.Dimension(800, 450));

        packagesToProcess.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        packagesToProcess.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        PackageListing.setViewportView(packagesToProcess);

        newPackageButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        newPackageButton.setText("NEW PACKAGE");
        newPackageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPackageButtonActionPerformed(evt);
            }
        });

        packetProgressBar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        packetProgressBar.setPreferredSize(new java.awt.Dimension(146, 10));

        javax.swing.GroupLayout PackagesLayout = new javax.swing.GroupLayout(Packages);
        Packages.setLayout(PackagesLayout);
        PackagesLayout.setHorizontalGroup(
            PackagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PackagesLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(PackagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newPackageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(packetProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(PackageListing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        PackagesLayout.setVerticalGroup(
            PackagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PackagesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(PackagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PackageListing, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PackagesLayout.createSequentialGroup()
                        .addComponent(newPackageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(packetProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Package Control", Packages);

        EmergencyButton.setIcon(EmergencyButtonNormal);
        EmergencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyButtonActionPerformed(evt);
            }
        });

        EmergencyButtonText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        EmergencyButtonText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmergencyButtonText.setText("Emergency Button");
        EmergencyButtonText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ConveyorText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ConveyorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConveyorText.setText("Conveyor Belt");
        ConveyorText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ConveyorButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ConveyorButton.setText("OFF");
        ConveyorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConveyorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MaintenanceLayout = new javax.swing.GroupLayout(Maintenance);
        Maintenance.setLayout(MaintenanceLayout);
        MaintenanceLayout.setHorizontalGroup(
            MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmergencyButtonText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MaintenanceLayout.createSequentialGroup()
                .addGroup(MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MaintenanceLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConveyorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConveyorText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MaintenanceLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(EmergencyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        MaintenanceLayout.setVerticalGroup(
            MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaintenanceLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(EmergencyButtonText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmergencyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(ConveyorText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConveyorButton)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        ConveyorButton.getAccessibleContext().setAccessibleName("ConveyorButton");

        jTabbedPane1.addTab("Maintenance Menu", Maintenance);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConveyorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConveyorButtonActionPerformed
        if(ConveyorButton.isSelected()){
            ConveyorButton.setText("ON");
        }
        else{
            ConveyorButton.setText("OFF");
        }
    }//GEN-LAST:event_ConveyorButtonActionPerformed

    private void EmergencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyButtonActionPerformed
        if(EmergencyButton.isSelected()){
          EmergencyButton.setIcon(EmergencyButtonPressed);
          emergency_meeting();
        }
        else{
           EmergencyButton.setIcon(EmergencyButtonNormal);
        }
    }//GEN-LAST:event_EmergencyButtonActionPerformed

    private void newPackageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPackageButtonActionPerformed
        packetProgressBar.setValue(0);
        //getPacket()
        packetProgressBar.setValue(10);
        //getIdentification()
        //first mag sensor packetProgressBar.setValue(30);
        //Gate sensor packetProgressBar.setValue(70);
        //sleep(10)
        //packetProgressBar.setValue(100);
        //sleep(10)
        
    }//GEN-LAST:event_newPackageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplitterLineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplitterLineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplitterLineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplitterLineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplitterLineUI().setVisible(true);
            }
        });
        
    }

    private void emergency_meeting(){
        InputStream sound;
        try{
            sound = new FileInputStream(new File("./sounds/EmergencyMeeting.wav"));
            AudioStream audio = new AudioStream(sound);
            AudioPlayer.player.start(audio);
        }
        catch(Exception e){
            System.out.println("Failed." + e);
        }
    }
    
    private void newPacketReg(int type){
        try{
            List<Packet> list = new ArrayList<>(); 
            for(int i = 0; i< packagesToProcess.getModel().getSize();i++){
                list.add(packagesToProcess.getModel().getElementAt(i));
            }
            
            Packet newP = new Packet(type);
            list.add(newP);
            
            Packet[] nlist = new Packet[list.size()];
            nlist = list.toArray(nlist);
            
            packagesToProcess.setListData(nlist);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    
    private Icon EmergencyButtonNormal = new ImageIcon("./images/ButtonNormal.png");
    private Icon EmergencyButtonPressed = new ImageIcon("./images/ButtonPressed.png");
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ConveyorButton;
    private javax.swing.JLabel ConveyorText;
    private javax.swing.JToggleButton EmergencyButton;
    private javax.swing.JLabel EmergencyButtonText;
    private javax.swing.JPanel Maintenance;
    private javax.swing.JScrollPane PackageListing;
    private javax.swing.JPanel Packages;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton newPackageButton;
    private javax.swing.JList<Packet> packagesToProcess;
    private javax.swing.JProgressBar packetProgressBar;
    // End of variables declaration//GEN-END:variables

}
